### ISSUE TITLE
Tests rely on specific users being present

### ISSUE THREAD

**Issue by gdude2002** [Adam01/Cylinder-server#3]
Instead of `test` and `sudouser` (and their passwords), these should be provided by environment variables.

(This is mostly because I already have a user named `test` on my machine)

**Comment by gdude2002** [comment]
If you *really* need to hardcode this, the users on my machine are `adam01` and `adam02` respectively, and have actual decent passwords.

**Comment by Adam01** [comment]
Can be easily done, the test user and password are initiated in the setupCls function.

**Comment by gdude2002** [comment]
I've made them available in the following variables.

* TEST_USER
* TEST_PASSWORD
* SUDO_USER
* SUDO_PASSWORD

Please do not print the passwords. xD

**Comment by Adam01** [comment]
Addressed in next commit.
