### ISSUE TITLE
File system exception handling

### ISSUE THREAD

**Issue by Adam01** [Adam01/Cylinder-server#5]
Exceptions raised during file system operations need to be dealt with and possible rethrown in a 'FileSystemError' class.

**Comment by gdude2002** [comment]
Eeeeh, why would you rethrow with a different exception class? That kinda defeats the point.

**Comment by Adam01** [comment]
Native OS exceptions are thrown - requiring better handling.

**Comment by gdude2002** [comment]
The same exceptions are thrown regardless of OS, aren't they?

**Comment by Adam01** [comment]
I'm getting ~exception.WindowsException in some cases.

**Comment by gdude2002** [comment]
You could just catch a superclass

**Comment by Adam01** [comment]
Yeah ended up just catching OSError inside fsoperations.
